### ISSUE TITLE
IndexOutOfBoundsException dans AdventurerAI

### ISSUE THREAD

**Issue by Freddrickk** [GitMyCode/Minesweeper-AI#28]
Cette exception est lancée occasionellement par AdventurerAI

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:635)
    at java.util.ArrayList.get(ArrayList.java:411)
    at minesweeper.ai.AdventurerAI.getSafestMove(AdventurerAI.java:86)
    at minesweeper.ai.AdventurerAI.addMovesWithProbabilities(AdventurerAI.java:76)
    at minesweeper.ai.AdventurerAI.addMovesToPlay(AdventurerAI.java:23)
    at minesweeper.ai.SafeOrRandomAI.getNextMoves(SafeOrRandomAI.java:56)
    at minesweeper.ai.AdventurerAI.getNextMoves(AdventurerAI.java:18)
    at minesweeper.ui.GameRunner.run(GameRunner.java:53)
    at minesweeper.ui.BoardGameView$2.run(BoardGameView.java:223)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Freddrickk** [comment]
Le tout survient empiriquement suite à cet indispensable constat :

> L'inconnu est fucking safe!

**Comment by Freddrickk** [comment]
Bugfix : https://github.com/GitMyCode/Minesweeper-AI/commit/9f136aaa0bf3f494dd3ca7604b6b374f73cd4c46

C'est hack-ish : Je regarde si la liste est vide, mais je crois que le problème provient plutôt d'une mauvaise probabilité calculé quelque part, une initialisation qui s'est pas faite ou un calcul qui retourne NaN. Ça arrivait en moyenne une fois par 30 parties, alors c'est pas mal négligeable. J'ai fait joué 500 parties sans problèmes.

**Comment by louib** [comment]
Ça arrive s'il n'y a aucune case non découverte à l'extérieur des frontières. Je vais régler ça sous peu.

**Comment by Freddrickk** [comment]
Ouin c'est pas mal ça que le fix fait.

**Comment by Freddrickk** [comment]
on se dit fixed ?
